### ISSUE TITLE
Не работают деревья в плагине LightCutter

### ISSUE THREAD

**Issue by kwilex** [kainlighty/LightCutterReborn#1]
Конфиг:
# 
# For WORLD Mode
# Without animations
config-version: 1.0
update-notification: false
language: ENGLISH
database-settings:
  storage: SQLite
  host: localhost
  base: lightcutter
  user: admin
  password: admin
  pool-size: 10
woodcutter-settings:
  mode: REGION
  economy: VAULT
  breaking-in-modes: true
  allow-drop: false
  disabled-worlds:
  - test
ky: HI
world-settings:
  messages-type: CHAT
  costs:
    oak_log: 1
    spruce_log: 2
    birch_log: 3-5
    jungle_log: 4
    acacia_log: 5-10
    dark_log: 6
region-settings:
  messages-type: ACTIONBAR
  regeneration:
    seconds: 5
    particle:
      enable: true
      type: EXPLOSION_NORMAL
      count: 4
    sound:
      enable: true
      type: BLOCK_WOOD_PLACE
      volume: 0.5

https://github.com/kainlighty/LightCutterReborn/assets/134966866/b0d0a6f4-f064-4cd7-95a3-8ffa46405001

**Comment by kainlighty** [comment]
1. Ядро и его версия
2. Версия ВГ
3. Лог загрузки плагина (все что свзяано с [LightCutter])
4. Что установлено в PlaceholderAPI (командой papi ecloud download что было скачано. Списком или скрином)
5. Какой приоритет у региона (например от спавна, если регион находится в регионе) - Это очень важный параметр

**Comment by kwilex** [comment]
1. Ядро Purpur 1.16.5
2. Версия ВГ 7.0.5
3 Лог:
[11:16:39] [Server thread/INFO]: [LightCutterReborn] Enabling LightCutterReborn v1.2.0
[11:16:39] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[11:16:39] [Server thread/INFO]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@4169b768
[11:16:39] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[11:16:39] [Server thread/INFO]: [LightCutterReborn] Regions [woodevent] successfully loaded
[11:16:39] [Server thread/INFO]: 
[11:16:39] [Server thread/INFO]:  » LightCutterReborn enabled
[11:16:39] [Server thread/INFO]:  » Version: 1.2.0
[11:16:39] [Server thread/INFO]: 
Всё что есть в логе связанное с Light Cutter
4. Expansion-vault.jar
Expansion-statistic.jar
Expansion-player.jar
5. Не находиться в других регионах кроме глобального.

**Comment by kwilex** [comment]
Спасибо заработало!!! С прошедшим новым годом!

**Comment by kainlighty** [comment]
Отлично! Взаимно :)

**Comment by Lextd** [comment]
У меня таже самая проблема, но загрузка библиотеки WG не помогла
У меня версия WG 7.0.4 переведенная на русский

**Comment by kainlighty** [comment]
> У меня таже самая проблема, но загрузка библиотеки WG не помогла У меня версия WG 7.0.4 переведенная на русский

Как видишь, раз у меня и у него работает, значит все в порядке.
Предоставь больше информации. Например, попробуй установить не перекомпилированную версию - оригинал, поможет ли? Плейсхолдеры по идее работает от API, поэтому не в курсе в чем может быть проблема.

**Comment by Lextd** [comment]
Я поставил WorldGuard обычный, версия 7.0.5. Но по прежнему не работает. Может ли это быть потому что я лесопилку делаю в регионе спавна?

**Comment by kainlighty** [comment]
> Я поставил WorldGuard обычный, версия 7.0.5. Но по прежнему не работает. Может ли это быть потому что я лесопилку делаю в регионе спавна?

Привет!

Спасибо за информацию.

Да, два региона могут мешать вычислять в каком регионе игрок. Поставь приоритет региону с лесопилкой выше, чем спавну. Например: /rg setpriority spawn 0, /rg setpriority wood 1.
Это должно помочь.

Позднее, я добавлю описание и распишу про эту проблему.

Отпиши, если это не поможет.
