### ISSUE TITLE
Проблема с настройкой

### ISSUE THREAD

**Issue by ghost** [kainlighty/LightCutterReborn#2]
Я не понимаю как его настроить вообще

**Comment by kainlighty** [comment]
Привет! 

Скоро добавлю документацию и распишу моменты, с которым часто обращались, и, думаю, ты найдёшь ответ на свой вопрос. 

А пока, если что-то непонятно, можешь написать тут.

**Comment by kainlighty** [comment]
Привет!

На GitHub обращение больше не рассматриваю.

Если появятся вопросы по поводу плагина, пожалуйста, создай тикет по [этой форме](https://forms.yandex.ru/cloud/66db55645d2a06399a5151f4).

Кстати, описание появится в следующих обновлениях.
