### ISSUE TITLE
LightCutter | Reborn

### ISSUE THREAD

**Issue by Semyonlife** [kainlighty/LightCutterReborn#3]
How to use this plugin???

**Comment by kainlighty** [comment]
Hi! 

I will add documentation soon and write down the points that were often addressed, and I think you will find the answer to your question. 

In the meantime, if something is unclear, you can write here.

**Comment by Semyonlife** [comment]
Hello, I downloaded the plugin, but it is not written anywhere how to use
it. Guides were also not filmed by anyone. Please tell me how to use it

чт, 2 мая 2024 г. в 23:54, Danil ***@***.***>:

**Comment by kainlighty** [comment]
Hi!

The WorldGuard extension from PlaceholderAPI is required for the plugin to work — `/papi ecloud download WorldGuard` → `/papi reload`.

---

In a future update, there will be a description of how to install the plugin, what commands are available, and a video review.

If you have any questions about the plugin, please create a request — nightofthekain@yandex.com
