### ISSUE TITLE
Проблема с настройкой 

### ISSUE THREAD

**Issue by LucazzF** [kainlighty/LightCutterReborn#4]
Здравствуйте, как сделать так чтобы когда ломалось дерево не кидались предупреждения от WorldGuard перерыл все настройки но не нашёл (

**Comment by kainlighty** [comment]
Привет!

Уведомление от WorldGuard приходить не должно, по крайней мере на версиях 1.19 и ниже.

Извини, сейчас нет времени потестировать и исправить. Как будет, посмотрю.

**Comment by kainlighty** [comment]
Привет!

На GitHub обращение больше не рассматриваю. Завёл задачу себе в своих инструментах.

Если хочешь следить за решением, пожалуйста, создай тикет по [этой форме](https://forms.yandex.ru/cloud/66db55645d2a06399a5151f4).
