### ISSUE TITLE
Error in the plugin itself related to two different regions

### ISSUE THREAD

**Issue by loeskeee** [kainlighty/LightCutterReborn#5]
Hi! There is a bug on my minecraft server which supports version 1.19.4. I recently installed your plugin on my server for lumberjacking, but there is a problem related to two different regions (pictures below), I have a huge lobby which is created under a single region: island, in the lobby itself there is a small island in which I would like the lumberjacking job system to run. After I created a separate region and called it forest, then after I started chopping wood with an axe, it started destroying this block, anyway, I will upload the video below at the youtube link. I do not know what to do and how do I combine these 2 regions so that firstly the player did not break the spavn, and secondly successfully extracted wood without any problems
![Снимок экрана 2024-08-24 012002](https://github.com/user-attachments/assets/9f1f4baf-aec9-41ad-9cca-b2452f1a5f7a)
As you can see, this little island and a large chunk of the lobby
YOUTUBE:
https://youtu.be/wbVmP-KYPfk

**Comment by kainlighty** [comment]
Привет!

Можно и на русском :)
![image](https://github.com/user-attachments/assets/2c48ae80-0b1a-4173-b396-6dfa27b6acc5)

Плагин детектит приоритетный регион, так как используются для этого плейсхолдеры.

Установи более высокий приоритет региону **forest**. Это должно помочь.

**Comment by loeskeee** [comment]
Привет! Ой извини, ну такое у меня бывает, уже привык. А как установить ему высокий приоритет?

**Comment by kainlighty** [comment]
> region setpriority

Да. Не помню, значение выше для **forest** или для другого нужно.

Попробуй, например, чтобы было 1 у **forest**, если не поможет, выдай ему 0, а другому 1. В общем, сделать наоборот.
