### ISSUE TITLE
Непонятно как работает плагин

### ISSUE THREAD

**Issue by FrandlyGG** [kainlighty/LightCutterReborn#6]
Опишите как работать с плагином, обрыл все форумы ничего не нашёл, никакой инструкции НИЧЕГО

Я создал регион wood после чего прописал /lc add wood 10 10 10
После чего ломаю дерево в этом же регионе, и ничего не происходит

**Comment by kainlighty** [comment]
Привет! Как будет время, я займусь этим вопросом со стороны кода.

Подобный вопрос решался в задаче #5
