### ISSUE TITLE
Вообще плагин отказываеться работать

### ISSUE THREAD

**Issue by KennyTV0** [kainlighty/LightCutterReborn#7]
Выдал права в пермишене игроку, сначала попробывал на основном спавне создать регион, ничего, никакой реакции нет, далее выдал приоритет, никакой реакции нет, окей, поставил регион отдельно от спавна с чистого листа так же никакой реакции просто пользователь видет "у вас нет прав для взаимодействия в этом регионе" 
Мой список действий по региону сначала выделить регион 2 точки я использовал //expand [] up-down
далле создал регион в worldguard, после чего уже прописал /lc add 10 10 10 для теста
плагин говорит что успешно созданно, регион в плагине совпадает с регионом worldguard, пробовал поменять название, так же 0 реакции, в общем по командам все прекрасно работает (хотя ничего не понятно ни обзоров ни документации в плагине никакой нет)
Но по факту как все сделаешь тупо пустота и да я снимал себя с прав, оставлял только user никаких проверок на fly на gm ничего, просто нет прав для этой территории, на овнере тоже самое, просто блоки ломаются и все никакой реакции
Буду благодарен за оперативный ответ и попытку решения
ядро purpur 1.16.5 последняя версия плагина (ставил ещё пред последнюю но ситуация та же) 
Если после ответа у меня все прекрасно заработает оставлю отзыв и инструкцию по использованию плагина

**Comment by kainlighty** [comment]
Привет!

Протестировал у себя на 1.20.2, все работает штатно.

Можешь, пожалуйста, прислать видео, иллюстрирующее ситуацию. Это поможет лучше разобраться в вопросе и посмотреть, что происходит на твоей стороне.

Также, если в консоли есть ошибки, пришли полный файл `latest.log`.

**Comment by kainlighty** [comment]
Также плагин переписан, пока лежит, нет времени сейчас вплотную заняться им. Как появится, релизну.

Протестированная версия уже есть, но перед выкладкой нужно будет убедиться, что всё работает хорошо.

**Comment by KennyTV0** [comment]
Да, конечно, завтра отправлю видео! Спасибо за ответ

**Comment by kainlighty** [comment]
Видео с моим тестом: https://youtu.be/imcUG4qMLxU

**Comment by KennyTV0** [comment]
https://disk.yandex.ru/i/ncI7x5iX8OmLqw
Извини что не на ютуб, однако видео можно посмотреть в источнике

**Comment by kainlighty** [comment]
> https://disk.yandex.ru/i/ncI7x5iX8OmLqw Извини что не на ютуб, однако видео можно посмотреть в источнике

Ничего, я работаю в Яндексе и Диск удобнее.

1. Включи в `config.yml` параметр `debug`, установив ему значение **true**.
2. Включи сервер.
3. После полного включения — выключи.
4. Приложи, например, на Диск (в папку, не архивом):
- `latest.log` из папки **logs**
- `config.yml` из папки плагина
- `lightcutter.db` из папки плагина.

Так как у меня работает, нужно посмотреть, что происходит на твоей стороне. Эти действия помогут разобраться в проблеме.

**Comment by KennyTV0** [comment]
https://disk.yandex.ru/d/7CL0iUaTSJmbQg Да, буду благодарен за ответ!

**Comment by kainlighty** [comment]
Привет!

Кажется, я разобрался в ситуации.

По логам не вижу загрузки расширения **WorldGuard** для **PlaceholderAPI**. Когда оно установлено, при запуске сервера в логах можно найти строчку `[PlaceholderAPI] Successfully registered expansion: worldguard [<версия>]`.

Его можно установить так:
- `/papi ecloud download WorldGuard`
- `/papi reload`.

Подробнее можешь прочитать тут — https://api.extendedclip.com/expansions/worldguard

Отпишись, пожалуйста, если помогло. Создам задачу на добавление в дебаг информации об этом.

**Comment by kainlighty** [comment]
В любом случае, этот пункт добавил себе.
![image](https://github.com/user-attachments/assets/818b4a3b-937e-43bb-89b3-1970ef7b8486)

**Comment by KennyTV0** [comment]
Да, спасибо тебе за помощь большое, и за довольно быстрый обратный ответ! Теперь плагин работает стабильно!
👍 
Для полного счастья не хватает плагина похожих работ на каких нибудь грузчиков или строителей (где по факту суть одна и та же) 
Дополню отзыв на spigot
